"""
Prometheus Metrics Instrumentation for Fraud Detection Pipeline
"""

from prometheus_client import Counter, Gauge, Histogram, Summary, generate_latest, CONTENT_TYPE_LATEST

# --- Transaction & Alert Counters ---
TOTAL_TRANSACTIONS = Counter(
    "total_transactions_processed",
    "Total financial transactions processed by the pipeline",
    ["type", "risk_level"]
)

NORMAL_TRANSACTIONS = Counter(
    "normal_transactions_total",
    "Total normal non-fraud transactions processed"
)

FRAUD_ALERTS = Counter(
    "fraud_alerts_total",
    "Total suspicious and fraudulent transaction alerts generated",
    ["risk_level", "model_used"]
)

TRANSACTIONS_PER_SECOND = Gauge(
    "transactions_per_second",
    "Current streaming throughput in transactions per second"
)

# --- Kafka Ingestion Metrics ---
KAFKA_MESSAGES_CONSUMED = Counter(
    "kafka_messages_consumed_total",
    "Total Kafka messages consumed from transactions topic"
)

KAFKA_ERRORS = Counter(
    "kafka_errors_total",
    "Total Kafka communication, decoding or connection errors",
    ["error_type"]
)

KAFKA_PROCESSING_LATENCY = Histogram(
    "kafka_processing_latency_seconds",
    "End-to-end Kafka delivery and processing latency in seconds",
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5]
)

# --- Machine Learning & Inference Metrics ---
ML_INFERENCE_LATENCY = Histogram(
    "ml_inference_latency_seconds",
    "Machine learning model scoring latency per transaction in seconds",
    ["model_mode"],
    buckets=[0.001, 0.002, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25]
)

MODEL_PREDICTION_COUNT = Counter(
    "model_prediction_count_total",
    "Total predictions generated by each model architecture",
    ["model_mode", "risk_level"]
)

MODEL_PREDICTION_ERRORS = Counter(
    "model_prediction_errors_total",
    "Total model inference exceptions or evaluation errors",
    ["model_mode"]
)

# --- Stream & Behavioral Profiling Latencies ---
STREAM_PROCESSING_LATENCY = Histogram(
    "stream_processing_latency_seconds",
    "Total stream processor pipeline latency per transaction in seconds",
    buckets=[0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5]
)

BEHAVIORAL_PROFILE_LATENCY = Histogram(
    "behavioral_profile_latency_seconds",
    "User behavioral profile lookup and calculation latency in seconds",
    buckets=[0.0005, 0.001, 0.002, 0.005, 0.01, 0.02, 0.05]
)

ACTIVE_ACCOUNTS = Gauge(
    "active_accounts",
    "Number of active user account profiles held in stateful memory"
)

# --- API & System Error Metrics ---
API_REQUEST_COUNT = Counter(
    "api_request_count_total",
    "Total HTTP API requests handled by FastAPI",
    ["method", "endpoint", "status_code"]
)

API_REQUEST_LATENCY = Histogram(
    "api_request_latency_seconds",
    "HTTP API request response latency in seconds",
    ["endpoint"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0]
)

SYSTEM_ERRORS = Counter(
    "system_errors_total",
    "Total unhandled system or infrastructure errors",
    ["component"]
)


def record_transaction_metrics(tx: dict, model_mode: str = "SUPERVISED_XGBOOST", stream_lat_s: float = 0.0):
    """Utility function to record transaction and latency metrics in one call."""
    tx_type = tx.get("type", "PAYMENT")
    risk_level = tx.get("risk_level", "LOW")
    is_fraud = tx.get("is_fraud", False)

    TOTAL_TRANSACTIONS.labels(type=tx_type, risk_level=risk_level).inc()
    
    if is_fraud or risk_level in ["HIGH", "CRITICAL"]:
        FRAUD_ALERTS.labels(risk_level=risk_level, model_used=model_mode).inc()
    else:
        NORMAL_TRANSACTIONS.inc()

    MODEL_PREDICTION_COUNT.labels(model_mode=model_mode, risk_level=risk_level).inc()

    ml_lat = tx.get("ml_latency_ms", 0.0) / 1000.0
    if ml_lat > 0:
        ML_INFERENCE_LATENCY.labels(model_mode=model_mode).observe(ml_lat)

    beh_lat = tx.get("behavioral_profile", {}).get("behavior_latency_ms", 0.0) / 1000.0
    if beh_lat > 0:
        BEHAVIORAL_PROFILE_LATENCY.observe(beh_lat)

    if stream_lat_s > 0:
        STREAM_PROCESSING_LATENCY.observe(stream_lat_s)
